image: docker:latest

before_script:
  - docker --version
#  - docker login -u admin -p greenhat http://10.48.19.45:8089

stages:
#  - build_frontend
  - build_frontend_docker
#  - build_backend
#  - build_backend_docker

#build_frontend:
#  image: node:14
#  stage: build_frontend
#  script:
#    - cd chat-frontend
#    - npm install --progress=false
#    - npm run build
#  artifacts:
#    paths:
#      - dist

build_frontend_docker:
  stage: build_frontend_docker
  script:
    - docker info
#    - docker login -u admin -p greenhat http://10.48.19.45:8089
    - docker login -u admin -p greenhat 10.48.19.45:8089/repository/Docker
    - cd chat-frontend
    - docker build -t 10.48.19.45:8089/frontend:latest .
    - docker push 10.48.19.45:8089/frontend:latest
#  only:
#    - master
#  when: manual

