version: '3.2'

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://10.48.19.45'
        gitlab_rails['gitlab_shell_ssh_port'] = 8822
    ports:
      - "80:80"
      - "8822:22"
    volumes:
      - $HOME/gitlab_server/settings/config:/etc/gitlab
      - $HOME/gitlab_server/settings/logs:/var/log/gitlab
      - $HOME/gitlab_server/settings/data:/var/opt/gitlab
    networks:
      - gitlab

  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    container_name: gitlab-runner
    restart: always
    depends_on:
      - gitlab
    volumes:
      - $HOME/gitlab_server/gitlab-runner:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - gitlab

  nexus:
    image: sonatype/nexus3
    ports:
      - "8089:8081"
    volumes:
      - nexus-data:/nexus-data

volumes:
  nexus-data:

networks:
  gitlab:
